/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoStoreFrontEnd;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author Naeem ur Rahman
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
    }

    String sub;
    String pay;
    String bal;
    String Date;
    String Time;
    String Cashier;

    Print(String sub, String pay, String bal, String Date, String Time, String Cashier, TableModel model) throws PrinterException {
        initComponents();

        this.sub = sub;
        this.pay = pay;
        this.bal = bal;
        this.Date = Date;
        this.Time = Time;
        this.Cashier = Cashier;

        txtPrint.setText(txtPrint.getText() + "**************************************************************************\n");
        txtPrint.setText(txtPrint.getText() + "************************** SUPER MARKET ****************************\n");
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "          " + String.format("%-25s", "Product") + String.format("%-25s", "Price") + String.format("%-25s", "Total") + "\n");
        for (int i = 0; i < model.getRowCount(); i++) {

            String Product = (String) model.getValueAt(i, 1);
            String Price = (String) model.getValueAt(i, 2);
            long Total = (long) model.getValueAt(i, 4);
            Product.trim();
            Price.trim();
            txtPrint.setText(txtPrint.getText() + "          " + String.format("%-25s", Product) + String.format("%-25s", Price) + String.format("%-25s", Total) + "\n");

        }
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "\n");
        txtPrint.setText(txtPrint.getText() + "          " + " SUB TOTAL  :  " + sub + "\n");
        txtPrint.setText(txtPrint.getText() + "          " + " PAY                :  " + pay + "\n");
        txtPrint.setText(txtPrint.getText() + "          " + " BALANCE     :  " + bal + "\n\n");
        txtPrint.setText(txtPrint.getText() + "***************************************************************************\n");
        txtPrint.setText(txtPrint.getText() + "***************************************************************************\n\n");
        txtPrint.setText(txtPrint.getText() + "          " + " CASHIER    :  " + Cashier + "\n\n");
        txtPrint.setText(txtPrint.getText() + "          " + " DATE    :  " + Date + "\n");
        txtPrint.setText(txtPrint.getText() + "          " + " TIME    :  " + Time + "\n\n");
        txtPrint.setText(txtPrint.getText() + "*****************    THANKS A LOT FOR YOUR COMING    *************\n");

        txtPrint.print();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Print Form");

        txtPrint.setColumns(20);
        txtPrint.setRows(5);
        jScrollPane1.setViewportView(txtPrint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPrint;
    // End of variables declaration//GEN-END:variables
}
